# Generated by Django 5.2.8 on 2026-06-11 13:01

import django.core.validators
import django.db.migrations.operations.special
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def migrar_status_para_producao(apps, schema_editor):
    Pedido = apps.get_model('portas', 'Pedido')
    Pedido.objects.filter(status__in=['corte', 'montagem']).update(status='producao')

class Migration(migrations.Migration):

    replaces = [('portas', '0001_initial'), ('portas', '0002_perfil_puxadores_compativeis_and_more'), ('portas', '0003_acabamento_espessuravidro_and_more'), ('portas', '0004_remove_vidrobase_acabamento_remove_vidrobase_modelo_and_more'), ('portas', '0005_perfil_vidros_compativeis_and_more'), ('portas', '0006_alter_vidrobase_espessura'), ('portas', '0007_divisor_encaixe_perfil_divisores_compativeis'), ('portas', '0008_cliente_alter_divisor_encaixe'), ('portas', '0009_cliente_ativo_orcamento_cliente'), ('portas', '0010_alter_cliente_options_remove_cliente_bairro_and_more'), ('portas', '0011_cliente_codigo_cliente_tipo_pessoa_and_more'), ('portas', '0012_alter_cliente_codigo'), ('portas', '0013_usuarioperfil'), ('portas', '0014_usuarioperfil_ativo_usuarioperfil_atualizado_em_and_more'), ('portas', '0015_alter_acabamento_nome_alter_puxador_acabamento_and_more'), ('portas', '0016_remove_divisor_tipo_remove_extraservico_tipo_and_more'), ('portas', '0017_perfilpuxador_fixacao_vidro'), ('portas', '0018_divisor_ativo_divisor_atualizado_em_and_more'), ('portas', '0019_alter_divisor_acabamento_and_more'), ('portas', '0020_alter_acabamento_nome_alter_divisor_codigo_and_more'), ('portas', '0021_remove_perfilpuxador_fixacao_vidro_and_more'), ('portas', '0022_pedido_pedidoitem'), ('portas', '0023_pedidoitem_qtd_divisor'), ('portas', '0024_adicional_pedidoitem'), ('portas', '0025_pedido_usuario'), ('portas', '0026_espessuravidro_chapa_dims'), ('portas', '0027_move_chapa_para_vidrobase'), ('portas', '0028_adicional_multiplo'), ('portas', '0029_bimerconfig'), ('portas', '0030_bimerconfig_schedule'), ('portas', '0031_bimer_id_e_config_precos'), ('portas', '0032_bimer_sync_clientes'), ('portas', '0033_configuracao_empresa'), ('portas', '0034_usuario_permissoes'), ('portas', '0035_permissoes_granulares'), ('portas', '0036_abatimento_mm_decimal'), ('portas', '0037_vidro_polido_custo_mao_obra_divisor_alturas'), ('portas', '0038_perfil_vidro_polido'), ('portas', '0039_puxador_sobreposto'), ('portas', '0040_configuracaoempresa_logo_claro'), ('portas', '0041_pedido_observacoes'), ('portas', '0042_remove_dead_models'), ('portas', '0043_indexes'), ('portas', '0044_pedidostatuslog'), ('portas', '0045_status_corte_montagem'), ('portas', '0046_cliente_cidade'), ('portas', '0047_pedido_data_previsao'), ('portas', '0048_pedidoitem_desconto'), ('portas', '0049_remove_divisor_alturas_desconto_percentual'), ('portas', '0050_pedido_bimer_erro'), ('portas', '0051_pedido_bimer_pedido_id'), ('portas', '0052_pedido_tipo_e_item_vidro'), ('portas', '0053_custo_mao_obra_vidro_e_backup'), ('portas', '0054_servico_vidro'), ('portas', '0055_remove_custo_mao_obra_vidro'), ('portas', '0056_bimerconfig_produto_ids'), ('portas', '0057_remove_bimer_id_produto_vidro'), ('portas', '0058_filas_corte_campos'), ('portas', '0059_remove_formato_vidro_add_corte_especial_servico'), ('portas', '0060_producao_status_e_montagem_feita'), ('portas', '0061_servicoporta_pedidoitemservicoporta'), ('portas', '0062_orcamento_status_e_expiracao'), ('portas', '0063_horario_limpeza_orcamento'), ('portas', '0064_token_monitor_publico'), ('portas', '0065_assistenteiaconfig'), ('portas', '0066_pedido_bimer_codigo'), ('portas', '0067_seguranca_auditoria')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Divisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acabamento', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExtraServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acabamento', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_porta', models.CharField(choices=[('AVULSO', 'Avulso'), ('1P_PUXADOR', '1x Perfil Puxador'), ('2P_PUXADOR', '2x Perfil Puxador'), ('LINHA_1000', 'Linha 1000'), ('VIDRO', 'Vidros')], max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acabamento', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilPuxador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acabamento', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Puxador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acabamento', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VidroBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acabamento', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('espessura_mm', models.PositiveIntegerField(default=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('quantidade', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('largura_m', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('altura_m', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('divisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portas.divisor')),
                ('extra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portas.extraservico')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='portas.orcamento')),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portas.perfil')),
                ('perfil_puxador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portas.perfilpuxador')),
                ('vidro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portas.vidrobase')),
            ],
        ),
        migrations.AddField(
            model_name='perfil',
            name='puxadores_compativeis',
            field=models.ManyToManyField(blank=True, related_name='perfis_compatíveis', to='portas.perfilpuxador'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='vidros_compativeis',
            field=models.ManyToManyField(blank=True, related_name='perfis_compatíveis', to='portas.vidrobase'),
        ),
        migrations.AlterField(
            model_name='divisor',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='extraservico',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='perfilpuxador',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='puxador',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vidrobase',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Acabamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EspessuraVidro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_mm', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='vidros_compativeis',
        ),
        migrations.RemoveField(
            model_name='vidrobase',
            name='espessura_mm',
        ),
        migrations.AddField(
            model_name='perfil',
            name='puxadores_simples_compativeis',
            field=models.ManyToManyField(blank=True, related_name='perfis_estrutura_compativeis', to='portas.puxador'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='puxadores_compativeis',
            field=models.ManyToManyField(blank=True, related_name='perfis_estrutura_compativeis', to='portas.perfilpuxador'),
        ),
        migrations.AlterField(
            model_name='divisor',
            name='acabamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portas.acabamento'),
        ),
        migrations.AlterField(
            model_name='extraservico',
            name='acabamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portas.acabamento'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='acabamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portas.acabamento'),
        ),
        migrations.AlterField(
            model_name='perfilpuxador',
            name='acabamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portas.acabamento'),
        ),
        migrations.AlterField(
            model_name='puxador',
            name='acabamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portas.acabamento'),
        ),
        migrations.AlterField(
            model_name='vidrobase',
            name='acabamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portas.acabamento'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='espessuras_vidro_compativeis',
            field=models.ManyToManyField(blank=True, related_name='perfis_compativeis', to='portas.espessuravidro'),
        ),
        migrations.AddField(
            model_name='vidrobase',
            name='espessura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vidros', to='portas.espessuravidro'),
        ),
        migrations.RemoveField(
            model_name='vidrobase',
            name='acabamento',
        ),
        migrations.RemoveField(
            model_name='vidrobase',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='vidrobase',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='divisor',
            name='acabamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portas.acabamento'),
        ),
        migrations.AlterField(
            model_name='divisor',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='divisor',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='espessuravidro',
            name='valor_mm',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='extraservico',
            name='acabamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portas.acabamento'),
        ),
        migrations.AlterField(
            model_name='extraservico',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='extraservico',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='acabamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portas.acabamento'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfilpuxador',
            name='acabamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portas.acabamento'),
        ),
        migrations.AlterField(
            model_name='perfilpuxador',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfilpuxador',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='puxador',
            name='acabamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portas.acabamento'),
        ),
        migrations.AlterField(
            model_name='puxador',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='puxador',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vidrobase',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vidrobase',
            name='espessura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portas.espessuravidro'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='vidros_compativeis',
            field=models.ManyToManyField(blank=True, related_name='perfis_compatíveis', to='portas.vidrobase'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='puxadores_simples_compativeis',
            field=models.ManyToManyField(blank=True, related_name='perfis_estrutura_puxador', to='portas.puxador'),
        ),
        migrations.AlterField(
            model_name='vidrobase',
            name='espessura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portas.espessuravidro'),
        ),
        migrations.AddField(
            model_name='divisor',
            name='encaixe',
            field=models.CharField(choices=[('embutir', 'Embutir'), ('sobrepor', 'Sobrepor')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='divisores_compativeis',
            field=models.ManyToManyField(blank=True, related_name='perfis_estrutura_divisor', to='portas.divisor'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pessoa', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2)),
                ('nome', models.CharField(max_length=255)),
                ('documento', models.CharField(blank=True, help_text='CPF ou CNPJ (somente números ou formatado).', max_length=20, null=True)),
                ('telefone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='divisor',
            name='encaixe',
            field=models.CharField(choices=[('embutido', 'Embutido'), ('aparente', 'Aparente')], max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos', to='portas.cliente'),
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='logradouro',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='tipo_pessoa',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='uf',
        ),
        migrations.AddField(
            model_name='cliente',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código (sistema externo)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_pessoa',
            field=models.CharField(blank=True, choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=2, null=True, verbose_name='Tipo de pessoa'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Código (sistema externo)'),
        ),
        migrations.CreateModel(
            name='UsuarioPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, unique=True)),
                ('tipo_usuario', models.CharField(choices=[('ADMIN', 'Administrador'), ('COMUM', 'Usuário comum')], default='COMUM', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acabamento',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='puxador',
            name='acabamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='portas.acabamento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='puxador',
            name='codigo',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='puxador',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='puxador',
            name='modelo',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='puxador',
            name='tipo',
            field=models.CharField(blank=True, default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='divisor',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='extraservico',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='perfilpuxador',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='puxador',
            name='tipo',
        ),
        migrations.AddField(
            model_name='divisor',
            name='abatimento_mm',
            field=models.IntegerField(default=0, help_text='Abate em mm na metragem do cálculo'),
        ),
        migrations.AddField(
            model_name='extraservico',
            name='abatimento_mm',
            field=models.IntegerField(default=0, help_text='Abate em mm na metragem do cálculo'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='abatimento_mm',
            field=models.IntegerField(default=0, help_text='Abate em mm na metragem do cálculo'),
        ),
        migrations.AddField(
            model_name='perfilpuxador',
            name='abatimento_mm',
            field=models.IntegerField(default=0, help_text='Abate em mm na metragem do cálculo'),
        ),
        migrations.AddField(
            model_name='puxador',
            name='abatimento_mm',
            field=models.IntegerField(default=0, help_text='Abate em mm na metragem do cálculo'),
        ),
        migrations.AlterField(
            model_name='divisor',
            name='codigo',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='extraservico',
            name='codigo',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='codigo',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='perfilpuxador',
            name='codigo',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='puxador',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vidrobase',
            name='codigo',
            field=models.CharField(max_length=6),
        ),
        migrations.AddField(
            model_name='perfilpuxador',
            name='fixacao_vidro',
            field=models.CharField(choices=[('face', 'Face'), ('canto', 'Canto')], default='canto', max_length=10, verbose_name='Fixação do vidro'),
        ),
        migrations.AddField(
            model_name='divisor',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='divisor',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='divisor',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extraservico',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='extraservico',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='extraservico',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilpuxador',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfilpuxador',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='perfilpuxador',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puxador',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='puxador',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='puxador',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vidrobase',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='divisor',
            name='acabamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portas.acabamento'),
        ),
        migrations.AlterField(
            model_name='extraservico',
            name='acabamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portas.acabamento'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='acabamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portas.acabamento'),
        ),
        migrations.AlterField(
            model_name='perfilpuxador',
            name='acabamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portas.acabamento'),
        ),
        migrations.AlterField(
            model_name='acabamento',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='divisor',
            name='codigo',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='espessuravidro',
            name='valor_mm',
            field=models.DecimalField(decimal_places=1, max_digits=4, unique=True),
        ),
        migrations.AlterField(
            model_name='extraservico',
            name='codigo',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='codigo',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='perfilpuxador',
            name='codigo',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='puxador',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vidrobase',
            name='codigo',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.RemoveField(
            model_name='perfilpuxador',
            name='fixacao_vidro',
        ),
        migrations.AddField(
            model_name='perfil',
            name='fixacao_vidro',
            field=models.CharField(choices=[('face', 'Face'), ('canto', 'Canto')], default='canto', max_length=10, verbose_name='Fixação do vidro'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('cancelado', 'Cancelado'), ('producao', 'Em produção'), ('concluido', 'Concluído')], default='aberto', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='portas.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('largura_mm', models.PositiveIntegerField()),
                ('altura_mm', models.PositiveIntegerField()),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('qtd_perfil_puxador', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('qtd_puxador', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('puxador_tamanho_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('acabamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portas.acabamento')),
                ('divisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portas.divisor')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='portas.pedido')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portas.perfil')),
                ('perfil_puxador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portas.perfilpuxador')),
                ('puxador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portas.puxador')),
                ('vidro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portas.vidrobase')),
            ],
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='qtd_divisor',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='adicional_obs',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='adicional_valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='espessuravidro',
            name='chapa_altura_mm',
            field=models.IntegerField(default=2000, verbose_name='Altura da chapa (mm)'),
        ),
        migrations.AddField(
            model_name='espessuravidro',
            name='chapa_largura_mm',
            field=models.IntegerField(default=3000, verbose_name='Largura da chapa (mm)'),
        ),
        migrations.RemoveField(
            model_name='espessuravidro',
            name='chapa_altura_mm',
        ),
        migrations.RemoveField(
            model_name='espessuravidro',
            name='chapa_largura_mm',
        ),
        migrations.AddField(
            model_name='vidrobase',
            name='chapa_altura_mm',
            field=models.IntegerField(default=2000, verbose_name='Altura da chapa (mm)'),
        ),
        migrations.AddField(
            model_name='vidrobase',
            name='chapa_largura_mm',
            field=models.IntegerField(default=3000, verbose_name='Largura da chapa (mm)'),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='adicional2_obs',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='adicional2_valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='adicional3_obs',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='adicional3_valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='adicional4_obs',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='adicional4_valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='BimerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(blank=True, verbose_name='URL base da API')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Usuário')),
                ('_password', models.CharField(blank=True, db_column='password', max_length=255, verbose_name='Senha')),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=False, verbose_name='Integração ativa')),
                ('ultima_sincronizacao', models.DateTimeField(blank=True, null=True)),
                ('log_sync', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Configuração Bimer',
            },
        ),
        migrations.AddField(
            model_name='bimerconfig',
            name='sync_dias_semana',
            field=models.CharField(default='mon,tue,wed,thu,fri,sat,sun', help_text='Abreviações separadas por vírgula: mon tue wed thu fri sat sun', max_length=100, verbose_name='Dias da semana'),
        ),
        migrations.AddField(
            model_name='bimerconfig',
            name='sync_horarios',
            field=models.CharField(default='7,14', help_text='Horas do dia separadas por vírgula (ex: 7,14 = 07:00 e 14:00)', max_length=100, verbose_name='Horários'),
        ),
        migrations.AddField(
            model_name='bimerconfig',
            name='identificador_empresa',
            field=models.CharField(blank=True, help_text='Código da empresa no Bimer (parâmetro identificadorEmpresa)', max_length=50, verbose_name='Identificador da empresa'),
        ),
        migrations.AddField(
            model_name='bimerconfig',
            name='identificador_tabela_precos',
            field=models.CharField(blank=True, help_text='Código da tabela de preços no Bimer (parâmetro identificadorTabelaPrecos)', max_length=50, verbose_name='Identificador da tabela de preços'),
        ),
        migrations.AddField(
            model_name='divisor',
            name='bimer_id',
            field=models.CharField(blank=True, help_text='Identificador interno obtido automaticamente via API Bimer', max_length=20, verbose_name='ID interno Bimer'),
        ),
        migrations.AddField(
            model_name='extraservico',
            name='bimer_id',
            field=models.CharField(blank=True, help_text='Identificador interno obtido automaticamente via API Bimer', max_length=20, verbose_name='ID interno Bimer'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='bimer_id',
            field=models.CharField(blank=True, help_text='Identificador interno obtido automaticamente via API Bimer', max_length=20, verbose_name='ID interno Bimer'),
        ),
        migrations.AddField(
            model_name='perfilpuxador',
            name='bimer_id',
            field=models.CharField(blank=True, help_text='Identificador interno obtido automaticamente via API Bimer', max_length=20, verbose_name='ID interno Bimer'),
        ),
        migrations.AddField(
            model_name='puxador',
            name='bimer_id',
            field=models.CharField(blank=True, help_text='Identificador interno obtido automaticamente via API Bimer', max_length=20, verbose_name='ID interno Bimer'),
        ),
        migrations.AddField(
            model_name='vidrobase',
            name='bimer_id',
            field=models.CharField(blank=True, help_text='Identificador interno obtido automaticamente via API Bimer', max_length=20, verbose_name='ID interno Bimer'),
        ),
        migrations.AddField(
            model_name='bimerconfig',
            name='identificador_caracteristica_clientes',
            field=models.CharField(blank=True, help_text='Filtra pessoas no Bimer por esta característica para importar como clientes', max_length=50, verbose_name='Identificador da característica (clientes)'),
        ),
        migrations.AddField(
            model_name='bimerconfig',
            name='log_sync_clientes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bimerconfig',
            name='ultima_sincronizacao_clientes',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='bimer_id',
            field=models.CharField(blank=True, help_text='Identificador obtido automaticamente via sincronização com o Bimer', max_length=20, verbose_name='ID interno Bimer'),
        ),
        migrations.CreateModel(
            name='ConfiguracaoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(default='Sistema Portas', max_length=100, verbose_name='Nome da empresa')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresa/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Configuração da Empresa',
            },
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='perm_cadastros',
            field=models.BooleanField(default=False, verbose_name='Cadastros'),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='perm_clientes',
            field=models.BooleanField(default=True, verbose_name='Clientes'),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='perm_pedidos',
            field=models.BooleanField(default=True, verbose_name='Pedidos'),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='perm_producao',
            field=models.BooleanField(default=True, verbose_name='Produção'),
        ),
        migrations.RemoveField(
            model_name='usuarioperfil',
            name='perm_cadastros',
        ),
        migrations.RemoveField(
            model_name='usuarioperfil',
            name='perm_clientes',
        ),
        migrations.RemoveField(
            model_name='usuarioperfil',
            name='perm_pedidos',
        ),
        migrations.RemoveField(
            model_name='usuarioperfil',
            name='perm_producao',
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='perm_cadastros_editar',
            field=models.BooleanField(default=False, verbose_name='Criar/editar cadastros'),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='perm_cadastros_excluir',
            field=models.BooleanField(default=False, verbose_name='Excluir cadastros'),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='perm_cadastros_ver',
            field=models.BooleanField(default=False, verbose_name='Ver cadastros'),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='perm_clientes_editar',
            field=models.BooleanField(default=True, verbose_name='Criar/editar clientes'),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='perm_clientes_excluir',
            field=models.BooleanField(default=False, verbose_name='Excluir clientes'),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='perm_clientes_ver',
            field=models.BooleanField(default=True, verbose_name='Ver clientes'),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='perm_pedidos_criar',
            field=models.BooleanField(default=True, verbose_name='Criar pedidos'),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='perm_pedidos_editar',
            field=models.BooleanField(default=True, verbose_name='Editar pedidos'),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='perm_pedidos_excluir',
            field=models.BooleanField(default=False, verbose_name='Excluir pedidos'),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='perm_pedidos_ver',
            field=models.BooleanField(default=True, verbose_name='Ver pedidos'),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='perm_producao_alterar_status',
            field=models.BooleanField(default=False, verbose_name='Alterar status'),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='perm_producao_ver',
            field=models.BooleanField(default=True, verbose_name='Ver produção'),
        ),
        migrations.AlterField(
            model_name='divisor',
            name='abatimento_mm',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Abate em mm na metragem do cálculo', max_digits=6),
        ),
        migrations.AlterField(
            model_name='extraservico',
            name='abatimento_mm',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Abate em mm na metragem do cálculo', max_digits=6),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='abatimento_mm',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Abate em mm na metragem do cálculo', max_digits=6),
        ),
        migrations.AlterField(
            model_name='perfilpuxador',
            name='abatimento_mm',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Abate em mm na metragem do cálculo', max_digits=6),
        ),
        migrations.AlterField(
            model_name='puxador',
            name='abatimento_mm',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Abate em mm na metragem do cálculo', max_digits=6),
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='custo_mao_obra',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor fixo adicionado em cada porta calculada', max_digits=10, verbose_name='Custo m�o de obra (por porta)'),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='divisor_altura_1',
            field=models.PositiveIntegerField(blank=True, help_text='Posicao do 1o divisor a partir da base (mm)', null=True, verbose_name='Altura divisor 1 (mm)'),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='divisor_altura_2',
            field=models.PositiveIntegerField(blank=True, help_text='Posicao do 2o divisor a partir da base (mm)', null=True, verbose_name='Altura divisor 2 (mm)'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='vidro_polido',
            field=models.BooleanField(default=False, help_text='Se marcado, adiciona 2mm em cada dimensao do vidro', verbose_name='Vidro polido'),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='puxador_sobreposto',
            field=models.BooleanField(default=True, verbose_name='Puxador sobreposto'),
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='logo_claro',
            field=models.ImageField(blank=True, help_text='Versão do logo para uso em fundo branco (impressão). Opcional — se não preenchido, usa o logo principal com fundo escuro.', null=True, upload_to='empresa/', verbose_name='Logo (fundo claro/impressão)'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ItemOrcamento',
        ),
        migrations.DeleteModel(
            name='Orcamento',
        ),
        migrations.DeleteModel(
            name='ExtraServico',
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['status'], name='pedido_status_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['data'], name='pedido_data_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['status', 'data'], name='pedido_status_data_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['bimer_id'], name='cliente_bimer_id_idx'),
        ),
        migrations.CreateModel(
            name='PedidoStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('cancelado', 'Cancelado'), ('producao', 'Em produção'), ('wise', 'Wise'), ('concluido', 'Concluído')], max_length=20)),
                ('alterado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['alterado_em'],
            },
        ),
        migrations.RemoveIndex(
            model_name='cliente',
            name='cliente_bimer_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='pedido',
            name='pedido_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='pedido',
            name='pedido_data_idx',
        ),
        migrations.RemoveIndex(
            model_name='pedido',
            name='pedido_status_data_idx',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('cancelado', 'Cancelado'), ('producao', 'Em produção'), ('wise', 'Wise'), ('concluido', 'Concluído')], default='aberto', max_length=20),
        ),
        migrations.AddField(
            model_name='pedidostatuslog',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='portas.pedido'),
        ),
        migrations.AddField(
            model_name='pedidostatuslog',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunSQL(
            sql=["UPDATE portas_pedido SET status = 'corte' WHERE status = 'producao';", "UPDATE portas_pedidostatuslog SET status = 'corte' WHERE status = 'producao';"],
            reverse_sql=["UPDATE portas_pedido SET status = 'producao' WHERE status = 'corte';", "UPDATE portas_pedidostatuslog SET status = 'producao' WHERE status = 'corte';"],
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_previsao',
            field=models.DateField(blank=True, null=True, verbose_name='Previsão de entrega'),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Desconto (R$)'),
        ),
        migrations.RemoveField(
            model_name='pedidoitem',
            name='divisor_altura_1',
        ),
        migrations.RemoveField(
            model_name='pedidoitem',
            name='divisor_altura_2',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('cancelado', 'Cancelado'), ('corte', 'Aguardando Corte'), ('montagem', 'Aguardando Montagem'), ('wise', 'Wise'), ('concluido', 'Concluído')], default='aberto', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, verbose_name='Desconto (%)'),
        ),
        migrations.AlterField(
            model_name='pedidostatuslog',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('cancelado', 'Cancelado'), ('corte', 'Aguardando Corte'), ('montagem', 'Aguardando Montagem'), ('wise', 'Wise'), ('concluido', 'Concluído')], max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='bimer_erro',
            field=models.TextField(blank=True, default='', verbose_name='Erro ao enviar para o Bimer'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='bimer_pedido_id',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='ID do pedido no Bimer'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo',
            field=models.CharField(choices=[('porta', 'Porta'), ('vidro', 'Vidro')], default='porta', max_length=10, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='PedidoItemVidro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('largura_mm', models.PositiveIntegerField(verbose_name='Largura (mm)')),
                ('altura_mm', models.PositiveIntegerField(verbose_name='Altura (mm)')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('desconto', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, verbose_name='Desconto (%)')),
                ('adicional_valor', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('adicional_obs', models.CharField(blank=True, default='', max_length=255)),
                ('adicional2_valor', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('adicional2_obs', models.CharField(blank=True, default='', max_length=255)),
                ('adicional3_valor', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('adicional3_obs', models.CharField(blank=True, default='', max_length=255)),
                ('adicional4_valor', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('adicional4_obs', models.CharField(blank=True, default='', max_length=255)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_vidro', to='portas.pedido')),
                ('vidro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portas.vidrobase')),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracaoBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diretorio', models.CharField(blank=True, help_text='Caminho absoluto onde os backups serão salvos', max_length=500, verbose_name='Diretório de destino')),
                ('padrao_nome', models.CharField(default='portas_{data}_{hora}', help_text='Use {data} para AAAAMMDD, {hora} para HHMM. Ex: portas_{data}_{hora}', max_length=200, verbose_name='Padrão do nome do arquivo')),
                ('ativo', models.BooleanField(default=False, verbose_name='Agendamento ativo')),
            ],
            options={
                'verbose_name': 'Configuração de Backup',
            },
        ),
        migrations.CreateModel(
            name='HistoricoBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/hora')),
                ('arquivo', models.CharField(blank=True, max_length=500, verbose_name='Arquivo')),
                ('tamanho_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='Tamanho')),
                ('sucesso', models.BooleanField(default=True, verbose_name='Sucesso')),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem')),
            ],
            options={
                'verbose_name': 'Histórico de Backup',
                'verbose_name_plural': 'Histórico de Backups',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='custo_mao_obra_vidro',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor fixo adicionado em cada item de vidro calculado', max_digits=10, verbose_name='Custo mão de obra (por vidro)'),
        ),
        migrations.AlterField(
            model_name='configuracaoempresa',
            name='custo_mao_obra',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor fixo adicionado em cada porta calculada', max_digits=10, verbose_name='Custo mão de obra (por porta)'),
        ),
        migrations.CreateModel(
            name='AgendamentoBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('mon', 'Segunda-feira'), ('tue', 'Terça-feira'), ('wed', 'Quarta-feira'), ('thu', 'Quinta-feira'), ('fri', 'Sexta-feira'), ('sat', 'Sábado'), ('sun', 'Domingo')], max_length=3, verbose_name='Dia da semana')),
                ('horario', models.TimeField(verbose_name='Horário')),
            ],
            options={
                'verbose_name': 'Agendamento de Backup',
                'verbose_name_plural': 'Agendamentos de Backup',
                'ordering': ['dia_semana', 'horario'],
                'unique_together': {('dia_semana', 'horario')},
            },
        ),
        migrations.CreateModel(
            name='ServicoVidro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('preco_m2', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço por m² (R$)')),
                ('valor_fixo', models.DecimalField(decimal_places=2, default=0, help_text='Somado ao resultado de m² × preço. Use para cobranças fixas (ex: Jateado).', max_digits=10, verbose_name='Valor fixo adicional (R$)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
            ],
            options={
                'verbose_name': 'Serviço de Vidro',
                'verbose_name_plural': 'Serviços de Vidro',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='PedidoItemVidroServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor congelado no momento do pedido', max_digits=10, verbose_name='Valor calculado')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='portas.pedidoitemvidro')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portas.servicovidro', verbose_name='Serviço')),
            ],
        ),
        migrations.RemoveField(
            model_name='configuracaoempresa',
            name='custo_mao_obra_vidro',
        ),
        migrations.AddField(
            model_name='bimerconfig',
            name='bimer_id_produto_porta',
            field=models.CharField(blank=True, default='00A0000AU5', help_text="Identificador do produto 'Porta' usado ao enviar pedidos.", max_length=50, verbose_name='ID produto Porta no Bimer'),
        ),
        migrations.AlterField(
            model_name='bimerconfig',
            name='bimer_id_produto_porta',
            field=models.CharField(blank=True, default='00A0000AU5', help_text="Identificador do produto 'Porta' usado ao enviar pedidos. Para vidros, cada VidroBase possui seu próprio ID Bimer.", max_length=50, verbose_name='ID produto Porta no Bimer'),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='perfil_cortado',
            field=models.BooleanField(default=False, verbose_name='Perfil cortado'),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='vidro_cortado',
            field=models.BooleanField(default=False, verbose_name='Vidro cortado'),
        ),
        migrations.AddField(
            model_name='pedidoitemvidro',
            name='vidro_cortado',
            field=models.BooleanField(default=False, verbose_name='Vidro cortado'),
        ),
        migrations.AddField(
            model_name='vidrobase',
            name='formato',
            field=models.CharField(choices=[('retangular', 'Retangular'), ('organico', 'Orgânico (redondo, oval, etc.)')], default='retangular', max_length=20, verbose_name='Formato de corte'),
        ),
        migrations.RemoveField(
            model_name='vidrobase',
            name='formato',
        ),
        migrations.AddField(
            model_name='servicovidro',
            name='corte_especial',
            field=models.BooleanField(default=False, help_text='Itens com este serviço vão para a fila de vidros orgânicos (molde, redondo, oval, etc.)', verbose_name='Corte especial'),
        ),
        migrations.RunPython(
            code=migrar_status_para_producao,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='montagem_feita',
            field=models.BooleanField(default=False, verbose_name='Montagem feita'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('cancelado', 'Cancelado'), ('producao', 'Em Produção'), ('wise', 'Wise'), ('concluido', 'Concluído')], default='aberto', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedidostatuslog',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('cancelado', 'Cancelado'), ('producao', 'Em Produção'), ('wise', 'Wise'), ('concluido', 'Concluído')], max_length=20),
        ),
        migrations.CreateModel(
            name='ServicoPorta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo_calculo', models.CharField(choices=[('metro_linear_perfil', 'Metro linear de perfil (perfil + PP + puxador + divisor)'), ('m2_vidro', 'M² de vidro'), ('metro_linear_vidro', 'Metro linear de vidro (perímetro)')], max_length=25, verbose_name='Base de cálculo')),
                ('preco', models.DecimalField(decimal_places=2, help_text='Por metro linear ou por m², conforme a base de cálculo.', max_digits=10, verbose_name='Preço por unidade (R$)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
            ],
            options={
                'verbose_name': 'Serviço de Porta',
                'verbose_name_plural': 'Serviços de Porta',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='PedidoItemServicoPorta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor congelado no momento do pedido', max_digits=10, verbose_name='Valor calculado')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='portas.pedidoitem')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portas.servicoporta', verbose_name='Serviço')),
            ],
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='dias_expiracao_orcamento',
            field=models.PositiveIntegerField(default=30, help_text='Orçamentos mais antigos que este número de dias serão excluídos automaticamente. Use 0 para desativar.', verbose_name='Expiração de orçamentos (dias)'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('orcamento', 'Orçamento'), ('aberto', 'Aberto'), ('cancelado', 'Cancelado'), ('producao', 'Em Produção'), ('wise', 'Wise'), ('concluido', 'Concluído')], default='orcamento', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedidostatuslog',
            name='status',
            field=models.CharField(choices=[('orcamento', 'Orçamento'), ('aberto', 'Aberto'), ('cancelado', 'Cancelado'), ('producao', 'Em Produção'), ('wise', 'Wise'), ('concluido', 'Concluído')], max_length=20),
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='horario_limpeza_orcamento',
            field=models.TimeField(blank=True, help_text='Horário diário para exclusão automática de orçamentos expirados. Deixe em branco para desativar.', null=True, verbose_name='Horário da limpeza automática'),
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='token_monitor',
            field=models.UUIDField(default=uuid.uuid4, help_text='UUID gerado automaticamente. Use na URL das páginas públicas de monitor e agenda.', verbose_name='Token monitor/agenda público'),
        ),
        migrations.CreateModel(
            name='AssistenteIAConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_api_key', models.CharField(blank=True, db_column='gemini_api_key', max_length=255, verbose_name='Chave de API do Gemini')),
                ('modelo', models.CharField(blank=True, default='gemini-2.0-flash', help_text='Nome do modelo Gemini a ser usado (ex: gemini-2.0-flash)', max_length=100, verbose_name='Modelo')),
                ('ativo', models.BooleanField(default=False, verbose_name='Assistente ativo')),
                ('token_chat', models.UUIDField(default=uuid.uuid4, help_text='UUID gerado automaticamente. Use na URL do chat compartilhado com terceiros.', verbose_name='Token do chat público')),
                ('total_chamadas', models.PositiveIntegerField(default=0, verbose_name='Total de chamadas à IA')),
                ('ultima_chamada', models.DateTimeField(blank=True, null=True, verbose_name='Última chamada')),
            ],
            options={
                'verbose_name': 'Configuração do Assistente IA',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='bimer_pedido_codigo',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Código do pedido no Bimer'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='altura_mm',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='largura_mm',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='pedidoitemvidro',
            name='altura_mm',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Altura (mm)'),
        ),
        migrations.AlterField(
            model_name='pedidoitemvidro',
            name='largura_mm',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Largura (mm)'),
        ),
    ]
