# Generated by Django 5.2.8 on 2025-11-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='puxadores_compativeis',
            field=models.ManyToManyField(blank=True, related_name='perfis_compatíveis', to='portas.perfilpuxador'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='vidros_compativeis',
            field=models.ManyToManyField(blank=True, related_name='perfis_compatíveis', to='portas.vidrobase'),
        ),
        migrations.AlterField(
            model_name='divisor',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='extraservico',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='perfilpuxador',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='puxador',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vidrobase',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
    ]
