# Generated by Django 5.2.8 on 2025-11-28 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0002_perfil_puxadores_compativeis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acabamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EspessuraVidro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_mm', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='vidros_compativeis',
        ),
        migrations.RemoveField(
            model_name='vidrobase',
            name='espessura_mm',
        ),
        migrations.AddField(
            model_name='perfil',
            name='puxadores_simples_compativeis',
            field=models.ManyToManyField(blank=True, related_name='perfis_estrutura_compativeis', to='portas.puxador'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='puxadores_compativeis',
            field=models.ManyToManyField(blank=True, related_name='perfis_estrutura_compativeis', to='portas.perfilpuxador'),
        ),
        migrations.AlterField(
            model_name='divisor',
            name='acabamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portas.acabamento'),
        ),
        migrations.AlterField(
            model_name='extraservico',
            name='acabamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portas.acabamento'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='acabamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portas.acabamento'),
        ),
        migrations.AlterField(
            model_name='perfilpuxador',
            name='acabamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portas.acabamento'),
        ),
        migrations.AlterField(
            model_name='puxador',
            name='acabamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portas.acabamento'),
        ),
        migrations.AlterField(
            model_name='vidrobase',
            name='acabamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portas.acabamento'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='espessuras_vidro_compativeis',
            field=models.ManyToManyField(blank=True, related_name='perfis_compativeis', to='portas.espessuravidro'),
        ),
        migrations.AddField(
            model_name='vidrobase',
            name='espessura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vidros', to='portas.espessuravidro'),
        ),
    ]
