# Generated by Django 5.2.8 on 2025-11-28 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0003_acabamento_espessuravidro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vidrobase',
            name='acabamento',
        ),
        migrations.RemoveField(
            model_name='vidrobase',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='vidrobase',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='divisor',
            name='acabamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portas.acabamento'),
        ),
        migrations.AlterField(
            model_name='divisor',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='divisor',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='espessuravidro',
            name='valor_mm',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='extraservico',
            name='acabamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portas.acabamento'),
        ),
        migrations.AlterField(
            model_name='extraservico',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='extraservico',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='acabamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portas.acabamento'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfilpuxador',
            name='acabamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portas.acabamento'),
        ),
        migrations.AlterField(
            model_name='perfilpuxador',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfilpuxador',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='puxador',
            name='acabamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portas.acabamento'),
        ),
        migrations.AlterField(
            model_name='puxador',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='puxador',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vidrobase',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vidrobase',
            name='espessura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portas.espessuravidro',
        null=True, blank=True,),
        ),
    ]
