# Generated by Django 5.2.8 on 2025-11-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0004_remove_vidrobase_acabamento_remove_vidrobase_modelo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='vidros_compativeis',
            field=models.ManyToManyField(blank=True, related_name='perfis_compatíveis', to='portas.vidrobase'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='puxadores_simples_compativeis',
            field=models.ManyToManyField(blank=True, related_name='perfis_estrutura_puxador', to='portas.puxador'),
        ),
    ]
