# Generated by Django 5.2.8 on 2025-12-01 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0005_perfil_vidros_compativeis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vidrobase',
            name='espessura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portas.espessuravidro'),
        ),
    ]
