# Generated by Django 5.2.8 on 2025-12-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0006_alter_vidrobase_espessura'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisor',
            name='encaixe',
            field=models.CharField(choices=[('embutir', 'Embutir'), ('sobrepor', 'Sobrepor')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='divisores_compativeis',
            field=models.ManyToManyField(blank=True, related_name='perfis_estrutura_divisor', to='portas.divisor'),
        ),
    ]
