# Generated by Django 5.2.8 on 2025-12-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0007_divisor_encaixe_perfil_divisores_compativeis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pessoa', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2)),
                ('nome', models.CharField(max_length=255)),
                ('documento', models.CharField(blank=True, help_text='CPF ou CNPJ (somente números ou formatado).', max_length=20, null=True)),
                ('telefone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='divisor',
            name='encaixe',
            field=models.CharField(choices=[('embutido', 'Embutido'), ('aparente', 'Aparente')], max_length=20),
        ),
    ]
