# Generated by Django 5.2.8 on 2025-12-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0011_cliente_codigo_cliente_tipo_pessoa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Código (sistema externo)'),
        ),
    ]
