# Generated by Django 5.2.8 on 2025-12-18 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0014_usuarioperfil_ativo_usuarioperfil_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acabamento',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='puxador',
            name='acabamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='portas.acabamento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='puxador',
            name='codigo',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='puxador',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='puxador',
            name='modelo',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='puxador',
            name='tipo',
            field=models.CharField(blank=True, default=2, max_length=100),
            preserve_default=False,
        ),
    ]
