# Generated by Django 5.2.8 on 2025-12-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0015_alter_acabamento_nome_alter_puxador_acabamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divisor',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='extraservico',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='perfilpuxador',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='puxador',
            name='tipo',
        ),
        migrations.AddField(
            model_name='divisor',
            name='abatimento_mm',
            field=models.IntegerField(default=0, help_text='Abate em mm na metragem do cálculo'),
        ),
        migrations.AddField(
            model_name='extraservico',
            name='abatimento_mm',
            field=models.IntegerField(default=0, help_text='Abate em mm na metragem do cálculo'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='abatimento_mm',
            field=models.IntegerField(default=0, help_text='Abate em mm na metragem do cálculo'),
        ),
        migrations.AddField(
            model_name='perfilpuxador',
            name='abatimento_mm',
            field=models.IntegerField(default=0, help_text='Abate em mm na metragem do cálculo'),
        ),
        migrations.AddField(
            model_name='puxador',
            name='abatimento_mm',
            field=models.IntegerField(default=0, help_text='Abate em mm na metragem do cálculo'),
        ),
        migrations.AlterField(
            model_name='divisor',
            name='codigo',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='extraservico',
            name='codigo',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='codigo',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='perfilpuxador',
            name='codigo',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='puxador',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vidrobase',
            name='codigo',
            field=models.CharField(max_length=6),
        ),
    ]
