# Generated by Django 5.2.8 on 2025-12-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0016_remove_divisor_tipo_remove_extraservico_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilpuxador',
            name='fixacao_vidro',
            field=models.CharField(choices=[('face', 'Face'), ('canto', 'Canto')], default='canto', max_length=10, verbose_name='Fixação do vidro'),
        ),
    ]
