# Generated by Django 5.2.8 on 2026-01-30 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0018_divisor_ativo_divisor_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisor',
            name='acabamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portas.acabamento'),
        ),
        migrations.AlterField(
            model_name='extraservico',
            name='acabamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portas.acabamento'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='acabamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portas.acabamento'),
        ),
        migrations.AlterField(
            model_name='perfilpuxador',
            name='acabamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portas.acabamento'),
        ),
    ]
