# Generated by Django 5.2.8 on 2026-02-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0019_alter_divisor_acabamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acabamento',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='divisor',
            name='codigo',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='espessuravidro',
            name='valor_mm',
            field=models.DecimalField(decimal_places=1, max_digits=4, unique=True),
        ),
        migrations.AlterField(
            model_name='extraservico',
            name='codigo',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='codigo',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='perfilpuxador',
            name='codigo',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='puxador',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vidrobase',
            name='codigo',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
