# Generated by Django 5.2.8 on 2026-02-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0020_alter_acabamento_nome_alter_divisor_codigo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilpuxador',
            name='fixacao_vidro',
        ),
        migrations.AddField(
            model_name='perfil',
            name='fixacao_vidro',
            field=models.CharField(choices=[('face', 'Face'), ('canto', 'Canto')], default='canto', max_length=10, verbose_name='Fixação do vidro'),
        ),
    ]
