# Generated by Django 5.2.8 on 2026-02-10 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0021_remove_perfilpuxador_fixacao_vidro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('cancelado', 'Cancelado'), ('producao', 'Em produção'), ('concluido', 'Concluído')], default='aberto', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='portas.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('largura_mm', models.PositiveIntegerField()),
                ('altura_mm', models.PositiveIntegerField()),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('qtd_perfil_puxador', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('qtd_puxador', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('puxador_tamanho_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('acabamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portas.acabamento')),
                ('divisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portas.divisor')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='portas.pedido')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portas.perfil')),
                ('perfil_puxador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portas.perfilpuxador')),
                ('puxador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portas.puxador')),
                ('vidro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portas.vidrobase')),
            ],
        ),
    ]
