# Generated by Django 5.2.8 on 2026-02-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0022_pedido_pedidoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='qtd_divisor',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
