# Generated by Django 5.2.8 on 2026-02-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0023_pedidoitem_qtd_divisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='adicional_obs',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='adicional_valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
