# Generated by Django 5.2.8 on 2026-02-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0025_pedido_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='espessuravidro',
            name='chapa_altura_mm',
            field=models.IntegerField(default=2000, verbose_name='Altura da chapa (mm)'),
        ),
        migrations.AddField(
            model_name='espessuravidro',
            name='chapa_largura_mm',
            field=models.IntegerField(default=3000, verbose_name='Largura da chapa (mm)'),
        ),
    ]
