# Generated by Django 5.2.8 on 2026-02-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0026_espessuravidro_chapa_dims'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='espessuravidro',
            name='chapa_altura_mm',
        ),
        migrations.RemoveField(
            model_name='espessuravidro',
            name='chapa_largura_mm',
        ),
        migrations.AddField(
            model_name='vidrobase',
            name='chapa_altura_mm',
            field=models.IntegerField(default=2000, verbose_name='Altura da chapa (mm)'),
        ),
        migrations.AddField(
            model_name='vidrobase',
            name='chapa_largura_mm',
            field=models.IntegerField(default=3000, verbose_name='Largura da chapa (mm)'),
        ),
    ]
