# Generated by Django 5.2.8 on 2026-02-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0027_move_chapa_para_vidrobase'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='adicional2_obs',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='adicional2_valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='adicional3_obs',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='adicional3_valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='adicional4_obs',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='adicional4_valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
