# Generated by Django 5.2.8 on 2026-03-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0028_adicional_multiplo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BimerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(blank=True, verbose_name='URL base da API')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Usuário')),
                ('_password', models.CharField(blank=True, db_column='password', max_length=255, verbose_name='Senha')),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=False, verbose_name='Integração ativa')),
                ('ultima_sincronizacao', models.DateTimeField(blank=True, null=True)),
                ('log_sync', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Configuração Bimer',
            },
        ),
    ]
