# Generated by Django 5.2.8 on 2026-03-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0029_bimerconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimerconfig',
            name='sync_dias_semana',
            field=models.CharField(default='mon,tue,wed,thu,fri,sat,sun', help_text='Abreviações separadas por vírgula: mon tue wed thu fri sat sun', max_length=100, verbose_name='Dias da semana'),
        ),
        migrations.AddField(
            model_name='bimerconfig',
            name='sync_horarios',
            field=models.CharField(default='7,14', help_text='Horas do dia separadas por vírgula (ex: 7,14 = 07:00 e 14:00)', max_length=100, verbose_name='Horários'),
        ),
    ]
