# Generated by Django 5.2.8 on 2026-03-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0030_bimerconfig_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimerconfig',
            name='identificador_empresa',
            field=models.CharField(blank=True, help_text='Código da empresa no Bimer (parâmetro identificadorEmpresa)', max_length=50, verbose_name='Identificador da empresa'),
        ),
        migrations.AddField(
            model_name='bimerconfig',
            name='identificador_tabela_precos',
            field=models.CharField(blank=True, help_text='Código da tabela de preços no Bimer (parâmetro identificadorTabelaPrecos)', max_length=50, verbose_name='Identificador da tabela de preços'),
        ),
        migrations.AddField(
            model_name='divisor',
            name='bimer_id',
            field=models.CharField(blank=True, help_text='Identificador interno obtido automaticamente via API Bimer', max_length=20, verbose_name='ID interno Bimer'),
        ),
        migrations.AddField(
            model_name='extraservico',
            name='bimer_id',
            field=models.CharField(blank=True, help_text='Identificador interno obtido automaticamente via API Bimer', max_length=20, verbose_name='ID interno Bimer'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='bimer_id',
            field=models.CharField(blank=True, help_text='Identificador interno obtido automaticamente via API Bimer', max_length=20, verbose_name='ID interno Bimer'),
        ),
        migrations.AddField(
            model_name='perfilpuxador',
            name='bimer_id',
            field=models.CharField(blank=True, help_text='Identificador interno obtido automaticamente via API Bimer', max_length=20, verbose_name='ID interno Bimer'),
        ),
        migrations.AddField(
            model_name='puxador',
            name='bimer_id',
            field=models.CharField(blank=True, help_text='Identificador interno obtido automaticamente via API Bimer', max_length=20, verbose_name='ID interno Bimer'),
        ),
        migrations.AddField(
            model_name='vidrobase',
            name='bimer_id',
            field=models.CharField(blank=True, help_text='Identificador interno obtido automaticamente via API Bimer', max_length=20, verbose_name='ID interno Bimer'),
        ),
    ]
