# Generated by Django 5.2.8 on 2026-03-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0031_bimer_id_e_config_precos'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimerconfig',
            name='identificador_caracteristica_clientes',
            field=models.CharField(blank=True, help_text='Filtra pessoas no Bimer por esta característica para importar como clientes', max_length=50, verbose_name='Identificador da característica (clientes)'),
        ),
        migrations.AddField(
            model_name='bimerconfig',
            name='log_sync_clientes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bimerconfig',
            name='ultima_sincronizacao_clientes',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='bimer_id',
            field=models.CharField(blank=True, help_text='Identificador obtido automaticamente via sincronização com o Bimer', max_length=20, verbose_name='ID interno Bimer'),
        ),
    ]
