# Generated by Django 5.2.8 on 2026-03-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0032_bimer_sync_clientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(default='Sistema Portas', max_length=100, verbose_name='Nome da empresa')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresa/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Configuração da Empresa',
            },
        ),
    ]
