# Generated by Django 5.2.8 on 2026-03-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0033_configuracao_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioperfil',
            name='perm_cadastros',
            field=models.BooleanField(default=False, verbose_name='Cadastros'),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='perm_clientes',
            field=models.BooleanField(default=True, verbose_name='Clientes'),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='perm_pedidos',
            field=models.BooleanField(default=True, verbose_name='Pedidos'),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='perm_producao',
            field=models.BooleanField(default=True, verbose_name='Produção'),
        ),
    ]
