# Generated by Django 5.2.8 on 2026-03-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0034_usuario_permissoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioperfil',
            name='perm_cadastros',
        ),
        migrations.RemoveField(
            model_name='usuarioperfil',
            name='perm_clientes',
        ),
        migrations.RemoveField(
            model_name='usuarioperfil',
            name='perm_pedidos',
        ),
        migrations.RemoveField(
            model_name='usuarioperfil',
            name='perm_producao',
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='perm_cadastros_editar',
            field=models.BooleanField(default=False, verbose_name='Criar/editar cadastros'),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='perm_cadastros_excluir',
            field=models.BooleanField(default=False, verbose_name='Excluir cadastros'),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='perm_cadastros_ver',
            field=models.BooleanField(default=False, verbose_name='Ver cadastros'),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='perm_clientes_editar',
            field=models.BooleanField(default=True, verbose_name='Criar/editar clientes'),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='perm_clientes_excluir',
            field=models.BooleanField(default=False, verbose_name='Excluir clientes'),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='perm_clientes_ver',
            field=models.BooleanField(default=True, verbose_name='Ver clientes'),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='perm_pedidos_criar',
            field=models.BooleanField(default=True, verbose_name='Criar pedidos'),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='perm_pedidos_editar',
            field=models.BooleanField(default=True, verbose_name='Editar pedidos'),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='perm_pedidos_excluir',
            field=models.BooleanField(default=False, verbose_name='Excluir pedidos'),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='perm_pedidos_ver',
            field=models.BooleanField(default=True, verbose_name='Ver pedidos'),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='perm_producao_alterar_status',
            field=models.BooleanField(default=False, verbose_name='Alterar status'),
        ),
        migrations.AddField(
            model_name='usuarioperfil',
            name='perm_producao_ver',
            field=models.BooleanField(default=True, verbose_name='Ver produção'),
        ),
    ]
