# Generated by Django 5.2.8 on 2026-03-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0035_permissoes_granulares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisor',
            name='abatimento_mm',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Abate em mm na metragem do cálculo', max_digits=6),
        ),
        migrations.AlterField(
            model_name='extraservico',
            name='abatimento_mm',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Abate em mm na metragem do cálculo', max_digits=6),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='abatimento_mm',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Abate em mm na metragem do cálculo', max_digits=6),
        ),
        migrations.AlterField(
            model_name='perfilpuxador',
            name='abatimento_mm',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Abate em mm na metragem do cálculo', max_digits=6),
        ),
        migrations.AlterField(
            model_name='puxador',
            name='abatimento_mm',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Abate em mm na metragem do cálculo', max_digits=6),
        ),
    ]
