# Generated by Django 5.2.8 on 2026-03-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0036_abatimento_mm_decimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoempresa',
            name='custo_mao_obra',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor fixo adicionado em cada porta calculada', max_digits=10, verbose_name='Custo m�o de obra (por porta)'),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='divisor_altura_1',
            field=models.PositiveIntegerField(blank=True, help_text='Posicao do 1o divisor a partir da base (mm)', null=True, verbose_name='Altura divisor 1 (mm)'),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='divisor_altura_2',
            field=models.PositiveIntegerField(blank=True, help_text='Posicao do 2o divisor a partir da base (mm)', null=True, verbose_name='Altura divisor 2 (mm)'),
        ),
    ]
