# Generated by Django 5.2.8 on 2026-03-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0037_vidro_polido_custo_mao_obra_divisor_alturas'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='vidro_polido',
            field=models.BooleanField(default=False, help_text='Se marcado, adiciona 2mm em cada dimensao do vidro', verbose_name='Vidro polido'),
        ),
    ]
