# Generated by Django 5.2.8 on 2026-03-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0038_perfil_vidro_polido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='puxador_sobreposto',
            field=models.BooleanField(default=True, verbose_name='Puxador sobreposto'),
        ),
    ]
