# Generated by Django 5.2.8 on 2026-03-10 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0043_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('cancelado', 'Cancelado'), ('producao', 'Em produção'), ('wise', 'Wise'), ('concluido', 'Concluído')], max_length=20)),
                ('alterado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['alterado_em'],
            },
        ),
        migrations.RemoveIndex(
            model_name='cliente',
            name='cliente_bimer_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='pedido',
            name='pedido_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='pedido',
            name='pedido_data_idx',
        ),
        migrations.RemoveIndex(
            model_name='pedido',
            name='pedido_status_data_idx',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('cancelado', 'Cancelado'), ('producao', 'Em produção'), ('wise', 'Wise'), ('concluido', 'Concluído')], default='aberto', max_length=20),
        ),
        migrations.AddField(
            model_name='pedidostatuslog',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='portas.pedido'),
        ),
        migrations.AddField(
            model_name='pedidostatuslog',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
