# Generated by Django 5.2.8 on 2026-03-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0048_pedidoitem_desconto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoitem',
            name='divisor_altura_1',
        ),
        migrations.RemoveField(
            model_name='pedidoitem',
            name='divisor_altura_2',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('cancelado', 'Cancelado'), ('corte', 'Aguardando Corte'), ('montagem', 'Aguardando Montagem'), ('wise', 'Wise'), ('concluido', 'Concluído')], default='aberto', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, verbose_name='Desconto (%)'),
        ),
        migrations.AlterField(
            model_name='pedidostatuslog',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('cancelado', 'Cancelado'), ('corte', 'Aguardando Corte'), ('montagem', 'Aguardando Montagem'), ('wise', 'Wise'), ('concluido', 'Concluído')], max_length=20),
        ),
    ]
