# Generated by Django 5.2.8 on 2026-04-25 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0051_pedido_bimer_pedido_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo',
            field=models.CharField(choices=[('porta', 'Porta'), ('vidro', 'Vidro')], default='porta', max_length=10, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='PedidoItemVidro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('largura_mm', models.PositiveIntegerField(verbose_name='Largura (mm)')),
                ('altura_mm', models.PositiveIntegerField(verbose_name='Altura (mm)')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('desconto', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, verbose_name='Desconto (%)')),
                ('adicional_valor', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('adicional_obs', models.CharField(blank=True, default='', max_length=255)),
                ('adicional2_valor', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('adicional2_obs', models.CharField(blank=True, default='', max_length=255)),
                ('adicional3_valor', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('adicional3_obs', models.CharField(blank=True, default='', max_length=255)),
                ('adicional4_valor', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('adicional4_obs', models.CharField(blank=True, default='', max_length=255)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_vidro', to='portas.pedido')),
                ('vidro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portas.vidrobase')),
            ],
        ),
    ]
