# Generated by Django 5.2.8 on 2026-04-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0052_pedido_tipo_e_item_vidro'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diretorio', models.CharField(blank=True, help_text='Caminho absoluto onde os backups serão salvos', max_length=500, verbose_name='Diretório de destino')),
                ('padrao_nome', models.CharField(default='portas_{data}_{hora}', help_text='Use {data} para AAAAMMDD, {hora} para HHMM. Ex: portas_{data}_{hora}', max_length=200, verbose_name='Padrão do nome do arquivo')),
                ('ativo', models.BooleanField(default=False, verbose_name='Agendamento ativo')),
            ],
            options={
                'verbose_name': 'Configuração de Backup',
            },
        ),
        migrations.CreateModel(
            name='HistoricoBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/hora')),
                ('arquivo', models.CharField(blank=True, max_length=500, verbose_name='Arquivo')),
                ('tamanho_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='Tamanho')),
                ('sucesso', models.BooleanField(default=True, verbose_name='Sucesso')),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem')),
            ],
            options={
                'verbose_name': 'Histórico de Backup',
                'verbose_name_plural': 'Histórico de Backups',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='custo_mao_obra_vidro',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor fixo adicionado em cada item de vidro calculado', max_digits=10, verbose_name='Custo mão de obra (por vidro)'),
        ),
        migrations.AlterField(
            model_name='configuracaoempresa',
            name='custo_mao_obra',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor fixo adicionado em cada porta calculada', max_digits=10, verbose_name='Custo mão de obra (por porta)'),
        ),
        migrations.CreateModel(
            name='AgendamentoBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('mon', 'Segunda-feira'), ('tue', 'Terça-feira'), ('wed', 'Quarta-feira'), ('thu', 'Quinta-feira'), ('fri', 'Sexta-feira'), ('sat', 'Sábado'), ('sun', 'Domingo')], max_length=3, verbose_name='Dia da semana')),
                ('horario', models.TimeField(verbose_name='Horário')),
            ],
            options={
                'verbose_name': 'Agendamento de Backup',
                'verbose_name_plural': 'Agendamentos de Backup',
                'ordering': ['dia_semana', 'horario'],
                'unique_together': {('dia_semana', 'horario')},
            },
        ),
    ]
