# Generated by Django 5.2.8 on 2026-04-27 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0053_custo_mao_obra_vidro_e_backup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoVidro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('preco_m2', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço por m² (R$)')),
                ('valor_fixo', models.DecimalField(decimal_places=2, default=0, help_text='Somado ao resultado de m² × preço. Use para cobranças fixas (ex: Jateado).', max_digits=10, verbose_name='Valor fixo adicional (R$)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
            ],
            options={
                'verbose_name': 'Serviço de Vidro',
                'verbose_name_plural': 'Serviços de Vidro',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='PedidoItemVidroServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor congelado no momento do pedido', max_digits=10, verbose_name='Valor calculado')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='portas.pedidoitemvidro')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portas.servicovidro', verbose_name='Serviço')),
            ],
        ),
    ]
