# Generated by Django 5.2.8 on 2026-04-27 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0054_servico_vidro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaoempresa',
            name='custo_mao_obra_vidro',
        ),
    ]
