# Generated by Django 5.2.8 on 2026-04-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0056_bimerconfig_produto_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bimerconfig',
            name='bimer_id_produto_porta',
            field=models.CharField(blank=True, default='00A0000AU5', help_text="Identificador do produto 'Porta' usado ao enviar pedidos. Para vidros, cada VidroBase possui seu próprio ID Bimer.", max_length=50, verbose_name='ID produto Porta no Bimer'),
        ),
    ]
