# Generated by Django 5.2.8 on 2026-04-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0057_remove_bimer_id_produto_vidro'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='perfil_cortado',
            field=models.BooleanField(default=False, verbose_name='Perfil cortado'),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='vidro_cortado',
            field=models.BooleanField(default=False, verbose_name='Vidro cortado'),
        ),
        migrations.AddField(
            model_name='pedidoitemvidro',
            name='vidro_cortado',
            field=models.BooleanField(default=False, verbose_name='Vidro cortado'),
        ),
        migrations.AddField(
            model_name='vidrobase',
            name='formato',
            field=models.CharField(choices=[('retangular', 'Retangular'), ('organico', 'Orgânico (redondo, oval, etc.)')], default='retangular', max_length=20, verbose_name='Formato de corte'),
        ),
    ]
