# Generated by Django 5.2.8 on 2026-04-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0058_filas_corte_campos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vidrobase',
            name='formato',
        ),
        migrations.AddField(
            model_name='servicovidro',
            name='corte_especial',
            field=models.BooleanField(default=False, help_text='Itens com este serviço vão para a fila de vidros orgânicos (molde, redondo, oval, etc.)', verbose_name='Corte especial'),
        ),
    ]
