# Generated by Django 5.2.8 on 2026-04-28 13:00

from django.db import migrations, models


def migrar_status_para_producao(apps, schema_editor):
    Pedido = apps.get_model('portas', 'Pedido')
    Pedido.objects.filter(status__in=['corte', 'montagem']).update(status='producao')


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0059_remove_formato_vidro_add_corte_especial_servico'),
    ]

    operations = [
        migrations.RunPython(migrar_status_para_producao, migrations.RunPython.noop),
        migrations.AddField(
            model_name='pedidoitem',
            name='montagem_feita',
            field=models.BooleanField(default=False, verbose_name='Montagem feita'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('cancelado', 'Cancelado'), ('producao', 'Em Produção'), ('wise', 'Wise'), ('concluido', 'Concluído')], default='aberto', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedidostatuslog',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('cancelado', 'Cancelado'), ('producao', 'Em Produção'), ('wise', 'Wise'), ('concluido', 'Concluído')], max_length=20),
        ),
    ]
