# Generated by Django 5.2.8 on 2026-04-30 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0060_producao_status_e_montagem_feita'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoPorta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo_calculo', models.CharField(choices=[('metro_linear_perfil', 'Metro linear de perfil (perfil + PP + puxador + divisor)'), ('m2_vidro', 'M² de vidro'), ('metro_linear_vidro', 'Metro linear de vidro (perímetro)')], max_length=25, verbose_name='Base de cálculo')),
                ('preco', models.DecimalField(decimal_places=2, help_text='Por metro linear ou por m², conforme a base de cálculo.', max_digits=10, verbose_name='Preço por unidade (R$)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
            ],
            options={
                'verbose_name': 'Serviço de Porta',
                'verbose_name_plural': 'Serviços de Porta',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='PedidoItemServicoPorta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor congelado no momento do pedido', max_digits=10, verbose_name='Valor calculado')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='portas.pedidoitem')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portas.servicoporta', verbose_name='Serviço')),
            ],
        ),
    ]
