# Generated by Django 5.2.8 on 2026-05-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0061_servicoporta_pedidoitemservicoporta'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoempresa',
            name='dias_expiracao_orcamento',
            field=models.PositiveIntegerField(default=30, help_text='Orçamentos mais antigos que este número de dias serão excluídos automaticamente. Use 0 para desativar.', verbose_name='Expiração de orçamentos (dias)'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('orcamento', 'Orçamento'), ('aberto', 'Aberto'), ('cancelado', 'Cancelado'), ('producao', 'Em Produção'), ('wise', 'Wise'), ('concluido', 'Concluído')], default='orcamento', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedidostatuslog',
            name='status',
            field=models.CharField(choices=[('orcamento', 'Orçamento'), ('aberto', 'Aberto'), ('cancelado', 'Cancelado'), ('producao', 'Em Produção'), ('wise', 'Wise'), ('concluido', 'Concluído')], max_length=20),
        ),
    ]
