# Generated by Django 5.2.8 on 2026-05-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0062_orcamento_status_e_expiracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoempresa',
            name='horario_limpeza_orcamento',
            field=models.TimeField(blank=True, help_text='Horário diário para exclusão automática de orçamentos expirados. Deixe em branco para desativar.', null=True, verbose_name='Horário da limpeza automática'),
        ),
    ]
