# Generated by Django 5.2.8 on 2026-05-05 16:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0063_horario_limpeza_orcamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoempresa',
            name='token_monitor',
            field=models.UUIDField(default=uuid.uuid4, help_text='UUID gerado automaticamente. Use na URL das páginas públicas de monitor e agenda.', verbose_name='Token monitor/agenda público'),
        ),
    ]
