# Generated by Django 5.2.8 on 2026-06-08 13:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0064_token_monitor_publico'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistenteIAConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_api_key', models.CharField(blank=True, db_column='gemini_api_key', max_length=255, verbose_name='Chave de API do Gemini')),
                ('modelo', models.CharField(blank=True, default='gemini-2.0-flash', help_text='Nome do modelo Gemini a ser usado (ex: gemini-2.0-flash)', max_length=100, verbose_name='Modelo')),
                ('ativo', models.BooleanField(default=False, verbose_name='Assistente ativo')),
                ('token_chat', models.UUIDField(default=uuid.uuid4, help_text='UUID gerado automaticamente. Use na URL do chat compartilhado com terceiros.', verbose_name='Token do chat público')),
                ('total_chamadas', models.PositiveIntegerField(default=0, verbose_name='Total de chamadas à IA')),
                ('ultima_chamada', models.DateTimeField(blank=True, null=True, verbose_name='Última chamada')),
            ],
            options={
                'verbose_name': 'Configuração do Assistente IA',
            },
        ),
    ]
