# Generated by Django 5.2.8 on 2026-06-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0065_assistenteiaconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='bimer_pedido_codigo',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Código do pedido no Bimer'),
        ),
    ]
