# Generated by Django 5.2.8 on 2026-06-11 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portas', '0066_pedido_bimer_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='altura_mm',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='largura_mm',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='pedidoitemvidro',
            name='altura_mm',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Altura (mm)'),
        ),
        migrations.AlterField(
            model_name='pedidoitemvidro',
            name='largura_mm',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Largura (mm)'),
        ),
    ]
